<?php

class Register_Testmodule_Block_Manage_Testmodule_Edit_Tab_Form extends Mage_Adminhtml_Block_Widget_Form
{
    protected function _prepareForm()
    {
        $form = new Varien_Data_Form();
        $this->setForm($form);
        $fieldset = $form->addFieldset('testmodule_form', array('legend' => Mage::helper('testmodule')->__('Information')));

        $fieldset->addField(
            'title',
            'text',
            array(
                 'label'    => Mage::helper('testmodule')->__('Title'),
                 'class'    => 'required-entry',
                 'required' => true,
                 'name'     => 'title',
            )
        );


        return parent::_prepareForm();
    }
}