<?php

class Register_Testmodule_Block_Manage_Testmodule_Edit_Tabs extends Mage_Adminhtml_Block_Widget_Tabs
{
    public function __construct()
    {
        parent::__construct();
        $this->setId('testmodule_tabs');
        $this->setDestElementId('edit_form');
        $this->setTitle(Mage::helper('testmodule')->__('Information'));
    }

    protected function _beforeToHtml()
    {
        $this->addTab(
            'form_section',
            array(
                 'label'   => Mage::helper('testmodule')->__('Information'),
                 'title'   => Mage::helper('testmodule')->__('Information'),
                 'content' => $this->getLayout()->createBlock('testmodule/manage_testmodule_edit_tab_form')->toHtml(),
            )
        );

        $this->addTab(
            'collection_section',
            array(
                 'label'   => Mage::helper('testmodule')->__('Collection'),
                 'title'   => Mage::helper('testmodule')->__('Collection'),
                'content' => $this->getLayout()->createBlock('testmodule/manage_testmodule_edit_tab_collection')->toHtml(),
            )
        );

        return parent::_beforeToHtml();
    }
}