<?php

class Register_Testmodule_Block_Manage_Testmodule_Edit extends Mage_Adminhtml_Block_Widget_Form_Container
{
    public function __construct()
    {
        parent::__construct();

        $this->_objectId = 'id';
        $this->_blockGroup = 'testmodule';
        $this->_controller = 'manage_testmodule';

        $this->_updateButton('save', 'label', Mage::helper('testmodule')->__('Save'));
        $this->_updateButton('delete', 'label', Mage::helper('testmodule')->__('Delete'));
     
    }

    public function getHeaderText()
    {
      
            return Mage::helper('testmodule')->__('Test Module');
       
    }
}